name: Docker CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          docker_username: ${{ secrets.DOCKER_USERNAME }}
          docker_tokent: ${{ secrets.DOCKER_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: exercise_3
          push: true
          tags: ${{ DOCKER_USERNAME }}/my-app:latest
  
  # More jobs can be added
