name: Docker CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          docker_username: ${{ DOCKER_USERNAME }}
          docker_tokent: ${{ DOCKER_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
  
  # More jobs can be added
