name: Docker CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Add more steps here
      - name: Docker run
        run: docker Dockerfile
  
  # More jobs can be added
